# Generated by Django 2.0 on 2019-04-25 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190425_2150'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['init_time'], 'verbose_name': 'Route'},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='end_coord',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='timestamp',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='init_coord',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='step',
            name='speed',
        ),
        migrations.AddField(
            model_name='route',
            name='init_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='route',
            name='purchase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchase'),
            preserve_default=False,
        ),
    ]
