# Generated by Django 2.0 on 2019-04-20 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e16a7de-e1cd-47c3-b3a7-f31695f58ee0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
