# Generated by Django 2.0 on 2019-04-29 08:51

from django.db import migrations
import inventory.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='products',
            field=inventory.utils.fields.JSONField(default=dict),
        ),
    ]
